import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          dark: "hsl(var(--primary-dark))",
          "fixed-dim": "#cbbeff",
          "fixed": "#e7deff",
          "container": "#6332ed",
        },
        sidebar: "hsl(var(--sidebar))",
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        border: "hsl(var(--border))",
        "on-secondary": "#ffffff",
        "inverse-primary": "#cbbeff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e3e1ef",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "on-tertiary-fixed": "#1b1b25",
        "on-error": "#ffffff",
        "secondary": "#625a77",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1e0060",
        "secondary-fixed-dim": "#cbc2e2",
        "secondary-fixed": "#e8ddff",
        "on-surface-variant": "#484456",
        "surface-container-highest": "#dce2f3",
        "on-background": "#151c27",
        "inverse-on-surface": "#ebf1ff",
        "on-tertiary-container": "#d8d5e4",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c7c5d3",
        "surface-container": "#e7eefe",
        "inverse-surface": "#2a313d",
        "on-secondary-fixed": "#1e1830",
        "outline-variant": "#cac3d9",
        "on-secondary-fixed-variant": "#4a435e",
        "on-primary-container": "#dcd1ff",
        "surface-container-high": "#e2e8f8",
        "on-tertiary-fixed-variant": "#464651",
        "tertiary": "#454550",
        "tertiary-container": "#5d5c68",
        "error": "#ba1a1a",
        "surface-dim": "#d3daea",
        "outline": "#797487",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed-variant": "#4b00d3",
        "surface": "#f9f9ff",
        "on-surface": "#151c27",
        "on-secondary-container": "#68607d",
        "surface-tint": "#6433ee",
        "secondary-container": "#e8ddff",
        "surface-variant": "#dce2f3"
      },
      spacing: {
        "base": "8px",
        "section-gap": "120px",
        "stack-lg": "48px",
        "gutter": "24px",
        "stack-md": "24px",
        "container-padding": "24px",
        "stack-sm": "12px"
      },
      fontFamily: {
        "body-lg": ["var(--font-jakarta)", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "sans-serif"],
        "display-lg-mobile": ["var(--font-jakarta)", "sans-serif"],
        "display-lg": ["var(--font-jakarta)", "sans-serif"],
        "label-bold": ["var(--font-jakarta)", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "800" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-bold": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
export default config;
